# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac1ae5b64775c8edd53e8981aee19c2ce13cc0c223dd068560ea006f9bde849275162fe5ac23fe7e02ec071fb3672ca1e7990b07a29d54cf2bb2da24627a1471

test:
  secret_key_base: 9959529c7bbd9b4429bffdae87d3695d6832081a7178dfc760b5fead12ad6641702b5b57c5fb7cf5e8608076bab80c201f55dab27354c381f47573cab9b21ba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
